services:
  # runs the frontend
  app:
    container_name: app
    build:
      context: app
      dockerfile: Dockerfile.dev
    depends_on:
      api:
        condition: service_healthy
      mqtt:
        condition: service_started
    ports:
      - 8080:80
    volumes:
      - ./app:/app

  # runs the api
  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile.dev
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8081:80
    environment:
      DATABASE_URL: "mysql://root:password@database:3306/meshtastic-map?connection_limit=100"
    volumes:
      - ./api:/app
      - ./prisma:/app/prisma

  # listens to mqtt packets and saves to database
  mqtt:
    container_name: mqtt
    build:
      context: mqtt
      dockerfile: Dockerfile.dev
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://root:password@database:3306/meshtastic-map?connection_limit=100"
    volumes:
      - ./mqtt:/app
      - ./prisma:/app/prisma

  # runs the database to store everything from mqtt
  database:
    container_name: database
    image: bitnami/mariadb
    environment:
      MARIADB_DATABASE: "meshtastic-map"
      MARIADB_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306/tcp
    volumes:
      - database_data:/bitnami/mariadb
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_interval: 5s

  proxy:
    container_name: proxy
    image: nginx:alpine
    depends_on:
      app:
        condition: service_healthy
      api:
        condition: service_healthy
    ports:
      - 80:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test:
        ["CMD-SHELL", "wget -O- http://localhost/nginx/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_interval: 5s

volumes:
  database_data:
