FROM node:lts-alpine

WORKDIR /app

COPY package.json package-lock.json ./

COPY ./prisma /app/prisma

RUN npm install --frozen-lockfile

RUN npx prisma generate

EXPOSE 8080

CMD ["npm", "run", "dev"]