FROM node:lts-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --frozen-lockfile

HEALTHCHECK --interval=10s --timeout=5s --start-period=15s --retries=5 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:${HTTP_PORT:=80}/api/healthz || exit 1

CMD ["npm", "run", "dev"]